Webshop/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Webshop.Data;
using Webshop.Interfaces;
using Webshop.Models;
using Webshop.Viewmodels;

namespace Webshop.Controllers
{
    public class InventoryController : Controller
    {
        private static readonly InventoryViewModel inventoryViewModel = new InventoryViewModel();

        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IProductRepo _productRepo;
        private readonly ShoppingCart _shoppingCart;

        public InventoryController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IProductRepo productRepo, ShoppingCart shoppingCart)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _productRepo = productRepo;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Index()
        {          
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName");
            return View(new InventoryViewModel(_context.Inventory
                             .Include(product => product.Category)
                             .Include(product => product.ProductImage)
                             .ToList()
                             .Select(product => CreateProductViewModel(product))
                             .ToList()
            )) ;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminInventory()
        {
            return View(new AdminInventoryViewModel(new InventoryViewModel(_context.Inventory
                             .Include(product => product.Category)
                             .Include(product => product.ProductImage)
                             .ToList()
                             .Select(product => CreateProductViewModel(product))
                             .ToList(),
                            _context.Categories.ToList()
            )));
        }

        // GET: Inventory/CreateProduct
        [Authorize(Roles = "Admin")]
        public IActionResult CreateProduct()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName");

            return View();
        }

        // POST: Inventory/CreateProduct
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateProduct([Bind("Name,Price,Description,CategoryId,ImageTitle,ImageFile")] CreateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    CategoryId = model.CategoryId
                };

                if (model.ImageFile != null)
                {
                    ProductImageViewModel productImageToSend = new ProductImageViewModel();
                    productImageToSend.ImageFile = model.ImageFile;
                    productImageToSend.ImageTitle = model.ImageTitle;

                    string imageName = await ImageSaver.SaveImage(_context, _hostEnvironment, productImageToSend);

                    if (imageName != "empty")
                    {
                        var pr = _context.ProductImages
                        .Where(p => p.ImageName == imageName)
                        .FirstOrDefault();

                        if (pr != null)
                        {
                            product.ProductImageId = pr.ImageId;
                            _context.Inventory.Add(product);
                            await _context.SaveChangesAsync();
                        }
                    }
                }
                else
                {
                    //Insert record
                    _context.Inventory.Add(product);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(AdminInventory));
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? Id)
        {
            var product = _context.Inventory
                .Include(p => p.Category)
                .Include(p => p.ProductImage)
                .FirstOrDefault(p => p.Id == Id);

            ProductViewModel model = this.CreateProductViewModel(product);

            return View(model);
        }

        // POST: Inventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string errormessage;
            var productToDelete = await _context.Inventory.FindAsync(id);

            //todo-> combine these checks
            var productInCart = _context.CartContents
                        .Where(p => p.Product.Id == id)
                        .FirstOrDefault();

            var productInOrderDetails = _context.OrderDetails
                        .Where(od => od.ProductId == id)
                        .FirstOrDefault();

            if(productInCart != null)
            {
                errormessage = "Cant delete product '" + productToDelete.Name + "' because it exists in a cart!";
                return View("AdminInventory", new AdminInventoryViewModel((new InventoryViewModel(_context.Inventory
                             .Include(product => product.Category)
                             .Include(product => product.ProductImage)
                             .ToList()
                             .Select(product => CreateProductViewModel(product))
                             .ToList(),
                            _context.Categories.ToList()
            )), errormessage
            ));
            }
            if(productInOrderDetails != null)
            {
                errormessage =  "Cant delete product '" + productToDelete.Name + "' because it exists in an order!";
                return View("AdminInventory", new AdminInventoryViewModel((new InventoryViewModel(_context.Inventory
                             .Include(product => product.Category)
                             .Include(product => product.ProductImage)
                             .ToList()
                             .Select(product => CreateProductViewModel(product))
                             .ToList(),
                            _context.Categories.ToList()
            )), errormessage
            ));
            }

            else
            {
                //product is not inside a cart/orderdetail-> ok to delete
                _context.Inventory.Remove(productToDelete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(AdminInventory));
            }         
        }

        // GET: Inventory/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var productToEdit = await _context.Inventory.FindAsync(Id);
            if (productToEdit == null)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", productToEdit.Category);
            ViewData["ImageList"] = new List<ProductImage>(_context.ProductImages.ToList());

            return View(productToEdit);
        }

        // Post: Inventory/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id, Product product, int? imageId)
        {
            if (id != null)
            {
                if (ModelState.IsValid)
                {
                    Product productToChange = await _context.Inventory.FindAsync(id);

                    productToChange.CategoryId = product.CategoryId;
                    productToChange.Name = product.Name;
                    productToChange.Price = product.Price;
                    productToChange.Description = product.Description;
                    if(imageId != null)
                    {
                        if (imageId > 0)
                            productToChange.ProductImageId = imageId;
                        else
                            productToChange.ProductImageId = null;
                    }

                    _context.Inventory.Update(productToChange);

                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(AdminInventory));
        }

        private ProductViewModel CreateProductViewModel(Product product)
        {
            ProductViewModel model = new ProductViewModel();
            model.Id = product.Id;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.ProductImage = product.ProductImage;
            model.Category = product.Category;
            return model;
        }
    }
}

Webshop/Views/Inventory/AdminInventory.cshtml
@model Webshop.Viewmodels.AdminInventoryViewModel

@{
    ViewData["Title"] = "Admin Inventory";
}

<div class="container-fluid">

    <h1>Manage Inventory</h1>

    <a class="btn btn-primary" asp-area="" asp-controller="Inventory" asp-action="CreateProduct">Create new product</a>

    @if (Model.ErrorMessage != null)
    {
        <partial name="_ErrorMessagePartial" , model="@Model.ErrorMessage" />
    }

</div>

<partial name="PartialViews\_inventoryPartial" , model="@Model.InvViewModel" />

Webshop/Views/Inventory/CreateProduct.cshtml
@model Webshop.Viewmodels.CreateProductViewModel

@{
    ViewData["Title"] = "Create Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <h1>Create Product:</h1>

    <hr />

    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateProduct" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea class="form-control" asp-for="Description" rows="3"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryId" class="control-label"></label>
                    <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div><p>Optional image upload:</p></div>
                <div class="form-group">
                    <label asp-for="ImageTitle" class="control-label"></label>
                    <input asp-for="ImageTitle" class="form-control" />
                    <span asp-validation-for="ImageTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" accept="image/*" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create Product" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div>
        <a class="btn btn-primary" asp-action="AdminInventory">Back to List</a>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Webshop/Views/Inventory/Delete.cshtml
@model Webshop.Viewmodels.ProductViewModel

@{
    ViewData["Title"] = "Delete Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <h1>Delete Product</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Model.Name
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category.CategoryName)
            </dd>
            <dt class="col-sm-2">
                Uploaded Image
            </dt>
            <dd class="col-sm-10">
                @if (Model.ProductImage != null)
                {
                    <img src="@("~/Images/Productimages/"+Model.ProductImage.ImageName)" asp-append-version="true" width="250" height="250" />
                }
                else
                {
                    <img class="card" src="~/Images/example.jpg">
                }
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-primary" asp-action="AdminInventory">Back to List</a>
        </form>
    </div>

</div>

Webshop/Views/Inventory/Edit.cshtml
@model Webshop.Models.Product

@{
    ViewData["Title"] = "Edit Product";
}

<div class="container-fluid">

    <h1>Edit Product</h1>

    <div>
        <a class="btn btn-primary" asp-action="AdminInventory">Back to List</a>
    </div>

    <hr />

    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group col-md-8">
            <label asp-for="Description" class="control-label"></label>
            <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="row justify-content-evenly">
            <div class="col-2">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="col-2">
                <input type="submit" value="Edit without image change" class="btn btn-primary" />
            </div>
            <div class="col-2">
                <div class="card" style="width:200px">
                    @if (Model.ProductImage != null)
                    {
                        <img class="card" src="@("~/images/ProductImages/"+Model.ProductImage.ImageThumbName)" asp-append-version="true" />
                        <h4 class="card-title">Current Image</h4>
                    }
                    else
                    {
                        <img class="card" src="~/images/ProductImages/placeholderth.jpg">
                        <h4 class="card-title">Current placeholder image</h4>
                    }
                </div>
            </div>
        </div>

        <h1 class="h3">Pick new image:</h1>

        <div class="row">

            <div class="form-group col-auto">
                <button type="submit" name="imageId" value="-1">
                    <div class="card" style="width:200px">
                        <img class="card" src="~/images/ProductImages/placeholderth.jpg">
                        <h4 class="card-title">Placeholder</h4>
                    </div>
                </button>
            </div>

            @foreach (ProductImage item in ViewBag.ImageList)
            {
                <div class="form-group col-auto">
                    <button type="submit" name="imageId" value=@item.ImageId>
                        <div class="card" style="width:200px">
                            @if (Model != null)
                            {
                                <img class="card" src="@("~/images/ProductImages/"+item.ImageThumbName)" asp-append-version="true" /> }
                            else
                            {
                                <img class="card" src="~/Images/example.jpg">
                            }
                            <h4 class="card-title">@item.ImageTitle</h4>
                        </div>
                    </button>
                </div>
            }
        </div>
    </form>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Webshop/Views/Inventory/Index.cshtml
@model Webshop.Viewmodels.InventoryViewModel

<h1>List of products</h1>

<div>
    <h3>List of cupcakes</h3>
    <table class="table table-striped">
        <thead class="thead-light">
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                @if (User.IsInRole("Admin"))
                {
                <th>Edit</th>
                <th>Delete</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Inventory)
            {
                <tr>
                    <td>
                        @if (product.ProductImage != null)
                        {
                            <img src="@("~/images/ProductImages/"+product.ProductImage.ImageThumbName)" asp-append-version="true" /> }
                        else
                        {
                            <img src="@("~/images/ProductImages/placeholderth.jpg")" asp-append-version="true" />}
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => product.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => product.Category.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => product.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => product.Price)
                    </td>
                    <td>
                        <form asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@product.Id" method="post">
                            <input type="number" value="1" name="Quantity" />
                            <input type="submit" value="Add to cart" />
                        </form>
                    </td>

                    @if (User.IsInRole("Admin"))
                    {

                        <td>
                            <a asp-action="Edit" asp-route-id="@product.Id">Edit</a>
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@product.Id">Delete</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>